// // import { TemplateOne, TemplateTwo } from "../assets-20240903T162903Z-001/assets";

// import { TemplateOne, TemplateTwo } from "../assets-20240903T162903Z-001/assets";
// export const adminIds = ["FCfPhQAdDgXp3c0P3Ghy2SCkKdP2"];

// export const initialTags = [
//   "Software Engineer",
//   "Full-end Developer",
//   "Back-end Developer",
//   "Full-stack Developer",
//   "Web Developer",
//   "UI/UX Developer",
//   "Graphic Designer",
//   "Data Scientist",
//   "Product Manager",
//   "Project Manager",
//   "Sales Representative",
//   "Customer Service Representative",
//   "HR Manager",
//   "Financial Analyst",
//   "Content Writer",
//   "Teacher/Educator",
//   "Healthcare Professional",
//   "Legal Counsel",
// ];

// export const FiltersData = [
//   { id: "1", label: "Software Engineer", value: "Software Engineer" },
//   { id: "2", label: "Front-end Developer", value: "Front-end Developer" },
//   { id: "3", label: "Back-end Developer", value: "Back-end Developer" },
//   { id: "4", label: "Full-stack Developer", value: "Full-stack Developer" },
//   { id: "5", label: "Web Developer", value: "Web Developer" },
//   { id: "6", label: "UI/UX Designer", value: "UI/UX Designer" },
//   { id: "7", label: "Graphic Designer", value: "Graphic Designer" },
//   { id: "8", label: "Data Scientist", value: "Data Scientist" },
//   { id: "9", label: "Product Manager", value: "Product Manager" },
//   { id: "10", label: "Project Manager", value: "Project Manager" },
//   { id: "11", label: "Business Analyst", value: "Business Analyst" },
//   { id: "12", label: "Marketing Manager", value: "Marketing Manager" },
//   { id: "13", label: "Sales Representative", value: "Sales Representative" },
//   {
//     id: "14",
//     label: "Customer Service Representative",
//     value: "customer_service_representative",
//   },
//   { id: "15", label: "HR Manager", value: "hr_manager" },
//   { id: "16", label: "Financial Analyst", value: "financial_analyst" },
//   { id: "17", label: "Content Writer", value: "content_writer" },
//   { id: "18", label: "Teacher/Educator", value: "teacher_educator" },
//   {
//     id: "19",
//     label: "Healthcare Professional",
//     value: "healthcare_professional",
//   },
//   { id: "20", label: "Legal Counsel", value: "legal_counsel" },
// ];

// // export const TemplatesData = [
// //   { id: `template-${Date.now()}`, name: "Template1", component: TemplateOne },
// //   { id: `template-${Date.now()}`, name: "Template2", component: TemplateTwo },
// // ];

// // export const TemplatesData =  [
//   // {id :`template-${Date.now()}`, name : "Template1", component : Template }
// // ]

// export const TemplatesData = [
//   { id: 'template-1', name: "Template1", component: TemplateOne },
//   { id: 'template-2', name: "Template2", component: TemplateTwo },
// ];

import {
  Template1,
  Template11,
  Template12,
  Template13,
  Template14,
  Template15,
  Template16,
  Template17,
  Template18,
  Template19,
  Template2,
  Template20,
  Template21,
  Template22,
  Template23,
  Template24,
  Template25,
  Template26,
  Template27,
  Template28,
  Template29,
  Template3,
  Template30,
  Template31,
  Template32,
  Template33,
  Template34,
  Template35,
  Template36,
  Template37,
  Template38,
  Template39,
  Template4,
  Template40,
  Template41,
  Template42,
  Template43,
  Template44,
  Template45,
  Template46,
  Template47,
  Template48,
  Template49,
  Template5,
  Template50,
} from "../components/designs";
import Template10 from "../components/designs/Template10";
import Template6 from "../components/designs/Template6";
import Template7 from "../components/designs/Template7";
import Template8 from "../components/designs/Template8";
import Template9 from "../components/designs/Template9";

export const adminIds = ["109729022777570513634"];

export const initialTags = [
  "Software Engineer",
  "Front-end Developer",
  "Back-end Developer",
  "Full-stack Developer",
  "Web Developer",
  "UI/UX Designer",
  "Graphic Designer",
  "Data Scientist",
  "Product Manager",
  "Project Manager",
  "Business Analyst",
  "Marketing Manager",
  "Sales Representative",
  "Customer Service Representative",
  "HR Manager",
  "Financial Analyst",
  "Content Writer",
  "Teacher/Educator",
  "Healthcare Professional",
  "Legal Counsel",
];

export const FiltersData = [
  { id: "1", label: "Software Engineer", value: "Software Engineer" },
  { id: "2", label: "Front-end Developer", value: "Front-end Developer" },
  { id: "3", label: "Back-end Developer", value: "Back-end Developer" },
  { id: "4", label: "Full-stack Developer", value: "Full-stack Developer" },
  { id: "5", label: "Web Developer", value: "Web Developer" },
  { id: "6", label: "UI/UX Designer", value: "UI/UX Designer" },
  { id: "7", label: "Graphic Designer", value: "Graphic Designer" },
  { id: "8", label: "Data Scientist", value: "Data Scientist" },
  { id: "9", label: "Product Manager", value: "Product Manager" },
  { id: "10", label: "Project Manager", value: "Project Manager" },
  { id: "11", label: "Business Analyst", value: "Business Analyst" },
  { id: "12", label: "Marketing Manager", value: "Marketing Manager" },
  { id: "13", label: "Sales Representative", value: "Sales Representative" },
  {
    id: "14",
    label: "Customer Service Representative",
    value: "customer_service_representative",
  },
  { id: "15", label: "HR Manager", value: "hr_manager" },
  { id: "16", label: "Financial Analyst", value: "financial_analyst" },
  { id: "17", label: "Content Writer", value: "content_writer" },
  { id: "18", label: "Teacher/Educator", value: "teacher_educator" },
  {
    id: "19",
    label: "Healthcare Professional",
    value: "healthcare_professional",
  },
  { id: "20", label: "Legal Counsel", value: "legal_counsel" },
];

export const TemplatesData = [
  { id: `template-${Date.now()}`, name: "Template1", component: Template1 },
  { id: `template-${Date.now()}`, name: "Template2", component: Template2 },
  { id: `template-${Date.now()}`, name: "Template3", component: Template3 },
  { id: `template-${Date.now()}`, name: "Template4", component: Template4 },
  { id: `template-${Date.now()}`, name: "Template5", component: Template5 },
  { id: `template-${Date.now()}`, name: "Template6", component: Template6 },
  { id: `template-${Date.now()}`, name: "Template7", component: Template7 },
  { id: `template-${Date.now()}`, name: "Template8", component: Template8 },
  { id: `template-${Date.now()}`, name: "Template9", component: Template9 },
  { id: `template-${Date.now()}`, name: "Template10", component: Template10 },
  { id: `template-${Date.now()}`, name: "Template11", component: Template11 },
  { id: `template-${Date.now()}`, name: "Template12", component: Template12 },
  { id: `template-${Date.now()}`, name: "Template13", component: Template13 },
  { id: `template-${Date.now()}`, name: "Template14", component: Template14 },
  { id: `template-${Date.now()}`, name: "Template15", component: Template15 },
  { id: `template-${Date.now()}`, name: "Template16", component: Template16 },
  { id: `template-${Date.now()}`, name: "Template17", component: Template17 },
  { id: `template-${Date.now()}`, name: "Template18", component: Template18 },
  { id: `template-${Date.now()}`, name: "Template19", component: Template19 },
  { id: `template-${Date.now()}`, name: "Template20", component: Template20 },
  { id: `template-${Date.now()}`, name: "Template21", component: Template21 },
  { id: `template-${Date.now()}`, name: "Template22", component: Template22 },
  { id: `template-${Date.now()}`, name: "Template23", component: Template23 },
  { id: `template-${Date.now()}`, name: "Template24", component: Template24 },
  { id: `template-${Date.now()}`, name: "Template25", component: Template25 },
  { id: `template-${Date.now()}`, name: "Template26", component: Template26 },
  { id: `template-${Date.now()}`, name: "Template27", component: Template27 },
  { id: `template-${Date.now()}`, name: "Template28", component: Template28 },
  { id: `template-${Date.now()}`, name: "Template29", component: Template29 },
  { id: `template-${Date.now()}`, name: "Template30", component: Template30 },
  { id: `template-${Date.now()}`, name: "Template31", component: Template31 },
  { id: `template-${Date.now()}`, name: "Template32", component: Template32 },
  { id: `template-${Date.now()}`, name: "Template33", component: Template33 },
  { id: `template-${Date.now()}`, name: "Template34", component: Template34 },
  { id: `template-${Date.now()}`, name: "Template35", component: Template35 },
  { id: `template-${Date.now()}`, name: "Template36", component: Template36 },
  { id: `template-${Date.now()}`, name: "Template37", component: Template37 },
  { id: `template-${Date.now()}`, name: "Template38", component: Template38 },
  { id: `template-${Date.now()}`, name: "Template39", component: Template39 },
  { id: `template-${Date.now()}`, name: "Template40", component: Template40 },
  { id: `template-${Date.now()}`, name: "Template41", component: Template41 },
  { id: `template-${Date.now()}`, name: "Template42", component: Template42 },
  { id: `template-${Date.now()}`, name: "Template43", component: Template43 },
  { id: `template-${Date.now()}`, name: "Template44", component: Template44 },
  { id: `template-${Date.now()}`, name: "Template45", component: Template45 },
  { id: `template-${Date.now()}`, name: "Template46", component: Template46 },
  { id: `template-${Date.now()}`, name: "Template47", component: Template47 },
  { id: `template-${Date.now()}`, name: "Template48", component: Template48 },
  { id: `template-${Date.now()}`, name: "Template49", component: Template49 },
  { id: `template-${Date.now()}`, name: "Template50", component: Template50 },
 
];
